itou/api/urls.py
from django.urls import path
from rest_framework.authtoken import views as auth_views

from itou.api import views


# https://docs.djangoproject.com/en/dev/topics/http/urls/#url-namespaces-and-included-urlconfs
app_name = "api"

urlpatterns = [
    # TokenAuthentication endpoint to get token from login/password.
    path("token-auth/", auth_views.obtain_auth_token, name="token-auth"),
    path("dummy-employee-records/", views.DummyEmployeeRecordList.as_view(), name="dummy-employee-records"),
]

itou/www/autocomplete/urls.py
from django.urls import path

from itou.www.autocomplete import views


# https://docs.djangoproject.com/en/dev/topics/http/urls/#url-namespaces-and-included-urlconfs
app_name = "autocomplete"

urlpatterns = [
    path("cities", views.cities_autocomplete, name="cities"),
    path("jobs", views.jobs_autocomplete, name="jobs"),
    path("communes", views.communes_autocomplete, name="communes"),
]

itou/www/dashboard/urls.py
from django.urls import path

from itou.www.dashboard import views


# https://docs.djangoproject.com/en/dev/topics/http/urls/#url-namespaces-and-included-urlconfs
app_name = "dashboard"

urlpatterns = [
    path("", views.dashboard, name="index"),
    path("edit_user_email", views.edit_user_email, name="edit_user_email"),
    path("edit_user_info", views.edit_user_info, name="edit_user_info"),
    path("edit_user_preferences", views.edit_user_preferences, name="edit_user_preferences"),
    path("edit_job_seeker_info/<uuid:job_application_id>", views.edit_job_seeker_info, name="edit_job_seeker_info"),
    path("switch_siae", views.switch_siae, name="switch_siae"),
    path(
        "switch_prescriber_organization", views.switch_prescriber_organization, name="switch_prescriber_organization"
    ),
]

itou/www/dashboard/forms.py
from django import forms
from django.core.exceptions import ValidationError

from itou.job_applications.notifications import (
    NewQualifiedJobAppEmployersNotification,
    NewSpontaneousJobAppEmployersNotification,
)
from itou.users.models import User
from itou.utils.address.forms import AddressFormMixin
from itou.utils.widgets import DatePickerField, MultipleSwitchCheckboxWidget, SwitchCheckboxWidget


class EditUserInfoForm(AddressFormMixin, forms.ModelForm):
    """
    Edit a user profile.
    """

    email = forms.EmailField(label="Adresse électronique", widget=forms.TextInput(attrs={"autocomplete": "off"}))

    def __init__(self, *args, **kwargs):
        editor = kwargs.pop("editor")
        super().__init__(*args, **kwargs)

        if not self.instance.is_job_seeker or not editor.can_edit_email(self.instance):
            del self.fields["email"]

        if not self.instance.is_job_seeker:
            del self.fields["birthdate"]
            del self.fields["pole_emploi_id"]
            del self.fields["lack_of_pole_emploi_id_reason"]
        else:
            self.fields["phone"].required = True
            self.fields["birthdate"].required = True
            self.fields["birthdate"].widget = DatePickerField(
                {
                    "viewMode": "years",
                    "minDate": DatePickerField.min_birthdate().strftime("%Y/%m/%d"),
                    "maxDate": DatePickerField.max_birthdate().strftime("%Y/%m/%d"),
                    "useCurrent": False,
                    "allowInputToggle": False,
                }
            )
            self.fields["birthdate"].input_formats = [DatePickerField.DATE_FORMAT]

    class Meta:
        model = User
        fields = [
            "email",
            "first_name",
            "last_name",
            "birthdate",
            "phone",
            "address_line_1",
            "address_line_2",
            "post_code",
            "city",
            "city_slug",
            "pole_emploi_id",
            "lack_of_pole_emploi_id_reason",
        ]
        help_texts = {
            "birthdate": "Au format JJ/MM/AAAA, par exemple 20/12/1978",
            "phone": "Par exemple 0610203040",
        }

    def clean(self):
        super().clean()
        if self.instance.is_job_seeker:
            self._meta.model.clean_pole_emploi_fields(self.cleaned_data)


class EditUserEmailForm(forms.Form):

    email = forms.EmailField(
        label="Nouvelle adresse e-mail",
        required=True,
    )
    email_confirmation = forms.EmailField(
        label="Confirmation",
        required=True,
    )

    def __init__(self, *args, **kwargs):
        self.user_email = kwargs.pop("user_email")
        super().__init__(*args, **kwargs)

    def clean(self):
        super().clean()
        email = self.cleaned_data.get("email")
        email_confirmation = self.cleaned_data.get("email_confirmation")
        if email != email_confirmation:
            raise ValidationError("Les deux adresses sont différentes.")
        return self.cleaned_data

    def clean_email(self):
        email = self.cleaned_data["email"]
        if email == self.user_email:
            raise ValidationError("Veuillez indiquer une adresse différente de l'actuelle.")
        if User.objects.filter(email=email):
            raise ValidationError("Cette adresse est déjà utilisée par un autre utilisateur.")
        return email


class EditNewJobAppEmployersNotificationForm(forms.Form):
    spontaneous = forms.BooleanField(label="Candidatures spontanées", required=False, widget=SwitchCheckboxWidget())

    def __init__(self, *args, **kwargs):
        self.recipient = kwargs.pop("recipient")
        self.siae = kwargs.pop("siae")
        super().__init__(*args, **kwargs)
        self.fields["spontaneous"].initial = NewSpontaneousJobAppEmployersNotification.is_subscribed(self.recipient)

        if self.siae.job_description_through.exists():
            default_pks = self.siae.job_description_through.values_list("pk", flat=True)
            self.subscribed_pks = NewQualifiedJobAppEmployersNotification.recipient_subscribed_pks(
                recipient=self.recipient, default_pks=default_pks
            )
            choices = [
                (job_description.pk, job_description.display_name)
                for job_description in self.siae.job_description_through.all()
            ]
            self.fields["qualified"] = forms.MultipleChoiceField(
                label="Fiches de poste",
                required=False,
                widget=MultipleSwitchCheckboxWidget(),
                choices=choices,
                initial=self.subscribed_pks,
            )

    def save(self):
        if self.cleaned_data.get("spontaneous"):
            NewSpontaneousJobAppEmployersNotification.subscribe(recipient=self.recipient)
        else:
            NewSpontaneousJobAppEmployersNotification.unsubscribe(recipient=self.recipient)

        if self.siae.job_description_through.exists():
            to_subscribe_pks = self.cleaned_data.get("qualified")
            NewQualifiedJobAppEmployersNotification.replace_subscriptions(
                recipient=self.recipient, subscribed_pks=to_subscribe_pks
            )

itou/accounts/views/dashboard.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy

from allauth.account.views import PasswordChangeView


@login_required
def dashboard(request, template_name="account_itou/dashboard.html"):

    context = {}
    return render(request, template_name, context)


class ItouPasswordChangeView(PasswordChangeView):
    """
    https://github.com/pennersr/django-allauth/issues/468
    """

    success_url = reverse_lazy("accounts:dashboard")


password_change = login_required(ItouPasswordChangeView.as_view())

itou/www/dashboard/views.py
from allauth.account.views import LogoutView, PasswordChangeView
from django.conf import settings
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.utils.http import urlencode
from django.views.decorators.http import require_POST

from itou.job_applications.models import JobApplication, JobApplicationWorkflow
from itou.prescribers.models import PrescriberOrganization
from itou.siaes.models import Siae
from itou.utils.perms.siae import get_current_siae_or_404
from itou.utils.urls import get_safe_url
from itou.www.dashboard.forms import EditNewJobAppEmployersNotificationForm, EditUserEmailForm, EditUserInfoForm


@login_required
def dashboard(request, template_name="dashboard/dashboard.html"):
    can_show_financial_annexes = False
    can_show_employee_records = False
    job_applications_categories = []

    if request.user.is_siae_staff:
        siae = get_current_siae_or_404(request)
        can_show_financial_annexes = siae.convention_can_be_accessed_by(request.user)
        can_show_employee_records = siae.can_use_employee_record
        job_applications_categories = [
            {
                "name": "Candidatures à traiter",
                "states": [JobApplicationWorkflow.STATE_NEW, JobApplicationWorkflow.STATE_PROCESSING],
                "icon": "user-plus",
                "badge": "badge-danger",
            },
            {
                "name": "Candidatures acceptées ou mises en liste d'attente",
                "states": [JobApplicationWorkflow.STATE_ACCEPTED, JobApplicationWorkflow.STATE_POSTPONED],
                "icon": "user-check",
                "badge": "badge-secondary",
            },
            {
                "name": "Candidatures refusées/annulées",
                "states": [
                    JobApplicationWorkflow.STATE_REFUSED,
                    JobApplicationWorkflow.STATE_CANCELLED,
                    JobApplicationWorkflow.STATE_OBSOLETE,
                ],
                "icon": "user-x",
                "badge": "badge-secondary",
            },
        ]
        job_applications = siae.job_applications_received.values("state").all()
        for category in job_applications_categories:
            category["counter"] = len([ja for ja in job_applications if ja["state"] in category["states"]])
            category[
                "url"
            ] = f"{reverse('apply:list_for_siae')}?{'&'.join([f'states={c}' for c in category['states']])}"

    context = {
        "lemarche_regions": settings.LEMARCHE_OPEN_REGIONS,
        "job_applications_categories": job_applications_categories,
        "can_show_financial_annexes": can_show_financial_annexes,
        "can_show_employee_records": can_show_employee_records,
    }

    return render(request, template_name, context)


class ItouPasswordChangeView(PasswordChangeView):
    """
    https://github.com/pennersr/django-allauth/issues/468
    """

    success_url = reverse_lazy("dashboard:index")


password_change = login_required(ItouPasswordChangeView.as_view())


class ItouLogoutView(LogoutView):
    def post(self, *args, **kwargs):
        """
        We overload this method so that we can process the PEAMU callback
        when the user logs out.
        Original code:
        https://github.com/pennersr/django-allauth/blob/master/allauth/account/views.py#L775
        """
        peamu_id_token = self.request.user.peamu_id_token
        ajax_response = super().post(*args, **kwargs)
        if peamu_id_token:
            hp_url = self.request.build_absolute_uri("/")
            params = {"id_token_hint": peamu_id_token, "redirect_uri": hp_url}
            peamu_logout_url = f"{settings.PEAMU_AUTH_BASE_URL}/compte/deconnexion?{urlencode(params)}"
            return HttpResponseRedirect(peamu_logout_url)
        else:
            return ajax_response


logout = login_required(ItouLogoutView.as_view())


@login_required
def edit_user_email(request, template_name="dashboard/edit_user_email.html"):
    form = EditUserEmailForm(data=request.POST or None, user_email=request.user.email)
    if request.method == "POST" and form.is_valid():
        with transaction.atomic():
            request.user.email = form.cleaned_data["email"]
            request.user.save()
            request.user.emailaddress_set.first().delete()
        auth.logout(request)
        return HttpResponseRedirect("/")

    context = {
        "form": form,
    }

    return render(request, template_name, context)


@login_required
def edit_user_info(request, template_name="dashboard/edit_user_info.html"):
    """
    Edit a user.
    """
    dashboard_url = reverse_lazy("dashboard:index")
    prev_url = get_safe_url(request, "prev_url", fallback_url=dashboard_url)
    form = EditUserInfoForm(instance=request.user, editor=request.user, data=request.POST or None)
    extra_data = request.user.externaldataimport_set.pe_sources().first()

    if request.method == "POST" and form.is_valid():
        form.save()
        messages.success(request, "Mise à jour de vos informations effectuée !")
        success_url = get_safe_url(request, "success_url", fallback_url=dashboard_url)
        return HttpResponseRedirect(success_url)

    context = {
        "extra_data": extra_data,
        "form": form,
        "prev_url": prev_url,
    }

    return render(request, template_name, context)


def user_can_edit_job_seeker_info(user, job_application, current_siae_pk=None):
    return (
        # Only when the information is not managed by job seekers themselves
        job_application.has_editable_job_seeker
        and (
            # Same sender (no SQL)
            job_application.sender_id == user.id
            # Member of the SIAE that offers the job application
            or (current_siae_pk and current_siae_pk == job_application.to_siae_id)
            # Member of the authorized prescriber organization who propose the candidate to the job application
            or user.is_prescriber_of_authorized_organization(job_application.sender_prescriber_organization_id)
        )
    )


@login_required
def edit_job_seeker_info(request, job_application_id, template_name="dashboard/edit_job_seeker_info.html"):
    job_application = get_object_or_404(JobApplication.objects.select_related("job_seeker"), pk=job_application_id)
    current_siae_pk = request.session.get(settings.ITOU_SESSION_CURRENT_SIAE_KEY)
    if not user_can_edit_job_seeker_info(request.user, job_application, current_siae_pk):
        raise PermissionDenied

    dashboard_url = reverse_lazy("dashboard:index")
    back_url = get_safe_url(request, "back_url", fallback_url=dashboard_url)
    form = EditUserInfoForm(instance=job_application.job_seeker, editor=request.user, data=request.POST or None)

    if request.method == "POST" and form.is_valid():
        form.save()
        messages.success(request, "Les informations du candidat ont été mises à jour.")
        return HttpResponseRedirect(back_url)

    context = {
        "form": form,
        "job_application": job_application,
        "prev_url": back_url,
    }

    return render(request, template_name, context)


@login_required
@require_POST
def switch_siae(request):
    """
    Switch to the dashboard of another SIAE of the same SIREN.
    """
    dashboard_url = reverse_lazy("dashboard:index")

    pk = request.POST["siae_id"]
    queryset = Siae.objects.active_or_in_grace_period().member_required(request.user)
    siae = get_object_or_404(queryset, pk=pk)
    request.session[settings.ITOU_SESSION_CURRENT_SIAE_KEY] = siae.pk

    return HttpResponseRedirect(dashboard_url)


@login_required
@require_POST
def switch_prescriber_organization(request):
    """
    Switch prescriber organization for a user with multiple memberships.
    """
    dashboard_url = reverse_lazy("dashboard:index")

    pk = request.POST["prescriber_organization_id"]
    queryset = PrescriberOrganization.objects
    prescriber_organization = get_object_or_404(queryset, pk=pk)
    request.session[settings.ITOU_SESSION_CURRENT_PRESCRIBER_ORG_KEY] = prescriber_organization.pk

    return HttpResponseRedirect(dashboard_url)


@login_required
def edit_user_preferences(request, template_name="dashboard/edit_user_preferences.html"):
    if not request.user.is_siae_staff:
        raise PermissionDenied

    current_siae_pk = request.session.get(settings.ITOU_SESSION_CURRENT_SIAE_KEY)
    siae = get_object_or_404(Siae, pk=current_siae_pk)
    membership = request.user.siaemembership_set.get(siae=siae)
    new_job_app_notification_form = EditNewJobAppEmployersNotificationForm(
        recipient=membership, siae=siae, data=request.POST or None
    )

    dashboard_url = reverse_lazy("dashboard:index")
    back_url = get_safe_url(request, "back_url", fallback_url=dashboard_url)

    if request.method == "POST" and new_job_app_notification_form.is_valid():
        new_job_app_notification_form.save()
        messages.success(request, "Vos préférences ont été modifiées.")
        success_url = get_safe_url(request, "success_url", fallback_url=dashboard_url)
        return HttpResponseRedirect(success_url)

    context = {
        "new_job_app_notification_form": new_job_app_notification_form,
        "back_url": back_url,
    }

    return render(request, template_name, context)

itou/templates/dashboard/configure_jobs.html
{% extends "layout/content.html" %}
{% load bootstrap4 %}
{% load i18n %}

{% block title %}{% trans "Configurer vos fiches de postes" %}{{ block.super }}{% endblock %}

{% block content %}

    <h1>{% trans "Configurer vos fiches de postes" %}</h1>

    <h2 class="text-muted">{{ siae.display_name }}</h2>

    <form method="post" action="" class="d-block mt-3">

        {% csrf_token %}

        <table class="js-jobs-table table table-bordered table-striped table-responsive-sm text-center{% if not siae.jobs_through.exists %} d-none{% endif %}">
            <thead>
                <tr>
                    <th scope="col">{% trans "Recevoir<br>des<br>candidatures" %}</th>
                    <th scope="col" class="text-left">{% trans "Poste" %}</th>
                    <th scope="col">{% trans "ROME" %}</th>
                    <th scope="col">{% include "includes/icon.html" with icon="trash-2" %}</th>
                </tr>
            </thead>
            <tbody class="js-jobs-tbody">
                {% for job in siae.jobs_through.all %}
                {# Important: keep the JavaScript template in sync if you edit the row markup. #}
                <tr>
                    <td scope="row">
                        <input type="hidden" name="code" value="{{ job.appellation.code }}">
                        <input
                            type="checkbox"
                            name="is_active-{{ job.appellation.code }}"
                            {% if job.is_active %}checked{% endif %}>
                    </td>
                    <td class="text-left">
                        <p class="job-appellation-name">
                            <i>{{ job.appellation.name }}</i>
                        </p>
                        <div class="form-group">
                            <label for="custom-name-{{ job.appellation.code }}">
                                <small>{% trans "Nom personnalisé" %}</small>
                            </label>
                            <input
                                type="text"
                                class="form-control form-control-sm"
                                id="custom-name-{{ job.appellation.code }}"
                                name="custom-name-{{ job.appellation.code }}">
                            <small class="form-text text-muted">
                                {% trans "Si ce champ est renseigné, il sera utilisé à la place du nom par ci-dessus." %}
                            </small>
                        </div>
                        <div class="form-group">
                            <label for="description-{{ job.appellation.code }}">
                                <small>{% trans "Description" %}</small>
                            </label>
                            <textarea
                                class="form-control form-control-sm"
                                id="description-{{ job.appellation.code }}"
                                name="description-{{ job.appellation.code }}"
                                rows="3"></textarea>
                        </div>
                    </td>
                    <td>{{ job.appellation.rome.code }}</td>
                    <td><a href="#" role="button" class="js-job-delete">{% trans "Supprimer" %}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <label for="job-autocomplete-input">{% trans "Ajouter un métier :" %}</label>
        <div class="input-group mb-4">
            <div class="input-group-prepend">
                {# Loading #}
                <span class="input-group-text js-job-autocomplete-loading d-none">
                    <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                    <span class="sr-only">{% trans "Chargement..." %}</span>
                </span>
                {# No loading #}
                <span class="input-group-text js-job-autocomplete-no-loading">
                    {% include "includes/icon.html" with icon="plus" %}
                </span>
            </div>
            <input
                type="text"
                id="job-autocomplete-input"
                class="form-control js-job-autocomplete-input"
                aria-label="{% trans "Ajouter un métier" %}"
                data-autocomplete-source-url="{% url 'autocomplete:jobs' %}">
        </div>

        {% buttons %}
            <a class="btn btn-secondary" href="{% url 'dashboard:index' %}">{% trans "Annuler" %}</a>
            <button type="submit" class="btn btn-primary">{% trans "Enregistrer les modifications" %}</button>
        {% endbuttons %}

    </form>

{% endblock %}

itou/templates/dashboard/edit_job_seeker_info.html
{% extends "layout/content_small.html" %}
{% load bootstrap4 %}

{% block title %}Modification d'un candidat{{ block.super }}{% endblock %}

{% block content %}
<h1>Candidature de <span class="text-muted">{{ job_application.job_seeker.get_full_name|title }}</span></h1>

<form method="post" action="" class="js-prevent-multiple-submit">

    {% csrf_token %}

    {% bootstrap_form form alert_error_type="all" %}

    {% buttons %}
        <a class="btn btn-secondary" href="{{ prev_url }}">Annuler</a>
        <button type="submit" class="btn btn-primary">Enregistrer</button>
    {% endbuttons %}

</form>
{% endblock %}

{% block script %}
    {{ block.super }}
    <!-- Needed to use the Datepicker JS widget. -->
    {{ form.media }}
{% endblock %}

itou/templates/dashboard/edit_user_email.html
{% extends "layout/content_small.html" %}
{% load bootstrap4 %}

{% block title %}Modifier votre profil{{ block.super }}{% endblock %}

{% block content %}
<h1>Modifier votre adresse e-mail</h1>

<div class="alert alert-warning" role="alert">
    Ce changement entraînera une <b>déconnexion</b>.<br>
    Veuillez alors vous reconnecter avec votre nouvelle adresse e-mail.
</div>

<form method="post" action="" class="js-prevent-multiple-submit">
    {% csrf_token %}

    {% bootstrap_form form alert_error_type="all" %}

    <button type="submit" class="btn btn-primary">Enregistrer</button>
</form>

{% endblock %}

itou/templates/dashboard/edit_user_info.html
{% extends "layout/content_small.html" %}
{% load bootstrap4 %}

{% block title %}Modifier votre profil{{ block.super }}{% endblock %}

{% block content %}
<h1>Modifier votre profil</h1>

{% if extra_data %}

<div class="alert alert-info">

    Certains champs de ce formulaire sont pré-remplis avec des éléments en provenance de votre compte Pôle emploi 
    (récupérés lors de votre connexion du {{extra_data.created_at|date:"d F Y"}}).

</div>

{% endif %}

<form method="post" action="" class="js-prevent-multiple-submit">

    {% csrf_token %}

    {% bootstrap_form form alert_error_type="all" %}

    {% buttons %}
        <a class="btn btn-secondary" href="{{ prev_url }}">Annuler</a>
        <button type="submit" class="btn btn-primary">Enregistrer</button>
    {% endbuttons %}

</form>

{% endblock %}

{% block script %}
    {{ block.super }}
    <!-- Needed to use the Datepicker JS widget. -->
    {{ form.media }}
{% endblock %}

itou/templates/dashboard/edit_user_preferences.html
{% extends "layout/content_small.html" %}
{% load bootstrap4 %}

{% block title %}Préférences personnelles{{ block.super }}{% endblock %}

{% block content %}
<h1>Préférences personnelles</h1>
<h2><span class="text-muted">{{ current_siae.display_name }}</span></h2>

<div class="card-deck mt-3">
    <div class="card">
        <h3 class="card-header font-weight-bold h4">Notifications e-mail</h3>
        <div class="card-body">
                <h4 class="font-weight-bold h5">Nouvelles candidatures</h4>
                <form method="post" action="" class="js-prevent-multiple-submit">
                    {% csrf_token %}

                    {% bootstrap_form_errors new_job_app_notification_form %}
                    {% bootstrap_form new_job_app_notification_form field_class="custom-control custom-switch" show_label=False %}

                    {% buttons %}
                        <a class="btn btn-secondary" href="{{ back_url }}">Annuler</a>
                        <button type="submit" class="btn btn-primary">Enregistrer</button>
                    {% endbuttons %}

                </form>
        </div>
    </div>
</div>
{% endblock %}