itou/api/urls.py
from django.urls import path
from rest_framework.authtoken import views as auth_views

from itou.api import views


# https://docs.djangoproject.com/en/dev/topics/http/urls/#url-namespaces-and-included-urlconfs
app_name = "api"

urlpatterns = [
    # TokenAuthentication endpoint to get token from login/password.
    path("token-auth/", auth_views.obtain_auth_token, name="token-auth"),
    path("dummy-employee-records/", views.DummyEmployeeRecordList.as_view(), name="dummy-employee-records"),
]

itou/www/employee_record_views/urls.py
from django.urls import path

from itou.www.employee_record_views import views


app_name = "employee_record_views"

urlpatterns = [
    path("list", views.list, name="list"),
    path("create/<uuid:job_application_id>", views.create, name="create"),
    path("create_step_2/<uuid:job_application_id>", views.create_step_2, name="create_step_2"),
    path("create_step_3/<uuid:job_application_id>", views.create_step_3, name="create_step_3"),
]

itou/employee_record/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone

from itou.asp.models import EmployerType, PrescriberType, SiaeKind
from itou.job_applications.models import JobApplication
from itou.siaes.models import SiaeFinancialAnnex


# Validators


def validate_asp_batch_filename(value):
    """
    Simple validation of batch file name
    (ASP backend is picky about it)
    """
    if value and value.startswith("RIAE_FS_") and value.endswith(".json") and len(value) == 27:
        return
    raise ValidationError(f"Le format du nom de fichier ASP est incorrect: {value}")


class EmployeeRecordQuerySet(models.QuerySet):
    def ready(self):
        """
        These FS are ready to to be sent to ASP
        """
        return self.filter(status=EmployeeRecord.Status.READY)

    def sent(self):
        return self.filter(status=EmployeeRecord.Status.SENT)

    def sent_for_siae(self, siae):
        return self.sent().filter(job_application__to_siae=siae).select_related("job_application")

    def rejected(self):
        return self.filter(status=EmployeeRecord.Status.REJECTED)

    def rejected_for_siae(self, siae):
        return self.rejected().filter(job_application__to_siae=siae).select_related("job_application")

    def processed(self):
        return self.filter(status=EmployeeRecord.Status.PROCESSED)

    def processed_for_siae(self, siae):
        return self.processed().filter(job_application__to_siae=siae).select_related("job_application")

    def archived(self):
        """
        Archived employee records (completed and having a JSON archive)
        """
        return self.filter(status=EmployeeRecord.Status.ARCHIVED)

    def find_by_batch(self, filename, line_number):
        """
        Fetch a single employee record with ASP batch file input parameters
        """
        return self.filter(asp_batch_file=filename, asp_batch_line_number=line_number)


class EmployeeRecord(models.Model):
    """
    EmployeeRecord - Fiche salarié (FS for short)

    Holds information needed for JSON exports and processing by ASP
    """

    ERROR_JOB_APPLICATION_MUST_BE_ACCEPTED = "La candidature doit être acceptée"
    ERROR_JOB_APPLICATION_TOO_RECENT = "L'embauche a été validé trop récemment"
    ERROR_JOB_SEEKER_TITLE = "La civilité du salarié est obligatoire"
    ERROR_JOB_SEEKER_BIRTH_COUNTRY = "Le pays de naissance est obligatoire"
    ERROR_JOB_APPLICATION_WITHOUT_APPROVAL = "L'embauche n'est pas reliée à un PASS IAE"

    ERROR_JOB_SEEKER_TITLE = "La civilité du salarié est obligatoire"
    ERROR_JOB_SEEKER_BIRTH_COUNTRY = "Le pays de naissance est obligatoire"
    ERROR_JOB_SEEKER_HAS_NO_PROFILE = "Cet utilisateur n'a pas de profil de demandeur d'emploi enregistré"

    ERROR_EMPLOYEE_RECORD_IS_DUPLICATE = "Une fiche salarié pour ce PASS IAE et cette SIAE existe déjà"
    ERROR_EMPLOYEE_RECORD_INVALID_STATE = "La fiche salarié n'est pas dans l'état requis pour cette action"

    # 'C' stands for Creation
    ASP_MOVEMENT_TYPE = "C"

    class Status(models.TextChoices):
        """
        Status of the employee record

        Self-explanatory on the meaning, however:
        - an E.R. can be modified until it is in the PROCESSED state
        - after that, the FS is "archived" and can't be used for further interaction
        """

        NEW = "NEW", "Nouvelle fiche salarié"
        READY = "READY", "Données complètes, prêtes à l'envoi ASP"
        SENT = "SENT", "Envoyée ASP"
        REJECTED = "REJECTED", "Rejetée ASP"
        PROCESSED = "PROCESSED", "Traitée ASP"
        ARCHIVED = "ARCHIVED", "Archivée"

    created_at = models.DateTimeField(verbose_name=("Date de création"), default=timezone.now)
    updated_at = models.DateTimeField(verbose_name=("Date de modification"), default=timezone.now)
    status = models.CharField(max_length=10, verbose_name="Statut", choices=Status.choices, default=Status.NEW)

    # Job application has references on many mandatory parts of the E.R.:
    # - SIAE / asp id
    # - Employee
    # - Approval
    job_application = models.ForeignKey(
        "job_applications.jobapplication",
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="Candidature / embauche",
        related_name="employee_record",
    )

    # Employee records must be linked to a valid financial annex
    # This field can't be automatically filled, the user will be asked
    # to select a valid one manually
    financial_annex = models.ForeignKey(
        SiaeFinancialAnnex, verbose_name="Annexe financière", null=True, on_delete=models.SET_NULL
    )

    # These fields are duplicated to act as constraint fields on DB level
    approval_number = models.CharField(max_length=12, verbose_name="Numéro d'agrément")
    asp_id = models.IntegerField(verbose_name="Identifiant ASP de la SIAE")

    # ASP processing part
    asp_processing_code = models.CharField(max_length=4, verbose_name="Code de traitement ASP", null=True)
    asp_processing_label = models.CharField(max_length=100, verbose_name="Libellé de traitement ASP", null=True)

    # Employee records are sent to ASP in a JSON file,
    # We keep track of the name for processing feedback
    # The format of the file name is EXACTLY: RIAE_FS_ AAAAMMJJHHMMSS (27 chars)
    asp_batch_file = models.CharField(
        max_length=27,
        verbose_name="Fichier de batch ASP",
        null=True,
        db_index=True,
        validators=[validate_asp_batch_filename],
    )
    # Line number of the employee record in the batch file
    # Unique pair with `asp_batch_file`
    asp_batch_line_number = models.IntegerField(
        verbose_name="Ligne correspondante dans le fichier batch ASP", null=True, db_index=True
    )

    # Once correctly processed by ASP, the employee record is archived:
    # - it can't be changed anymore
    # - a serialized version of the employee record is stored (as proof, and for API concerns)
    # The API will not use JSON serializers on a regular basis,
    # except for the archive serialization, which occurs once.
    # It will only return a list of this JSON field for archived employee records.
    archived_json = models.JSONField(verbose_name="Archive JSON de la fiche salarié", null=True)

    objects = models.Manager.from_queryset(EmployeeRecordQuerySet)()

    class Meta:
        verbose_name = "Fiche salarié"
        verbose_name_plural = "Fiches salarié"
        constraints = [
            models.UniqueConstraint(fields=["asp_id", "approval_number"], name="unique_asp_id_approval_number")
        ]
        unique_together = ["asp_batch_file", "asp_batch_line_number"]
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.asp_id} - {self.approval_number} - {self.job_seeker}"

    def save(self, *args, **kwargs):
        if self.pk:
            self.updated_at = timezone.now()

        super().save(*args, **kwargs)

    def _clean_job_application(self):
        """
        Check if job application is valid for FS
        """

        if not self.job_application.state.is_accepted:
            raise ValidationError(self.ERROR_JOB_APPLICATION_MUST_BE_ACCEPTED)

        if not self.job_application.approval:
            raise ValidationError(self.ERROR_JOB_APPLICATION_WITHOUT_APPROVAL)

        if self.job_application.can_be_cancelled:
            raise ValidationError(self.ERROR_JOB_APPLICATION_TOO_RECENT)

    def _clean_job_seeker(self):
        """
        Check if data provided for the job seeker part of the FS is complete / valid
        """
        job_seeker = self.job_application.job_seeker

        # Check if user is "clean"
        job_seeker.clean()

        if not job_seeker.has_jobseeker_profile:
            raise ValidationError(self.ERROR_JOB_SEEKER_HAS_NO_PROFILE)

        # Further validation in the job seeker profile
        job_seeker.jobseeker_profile.clean()

    def clean(self):
        # see private methods above
        self._clean_job_application()
        self._clean_job_seeker()

    # Business methods

    def update_as_ready(self):
        """
        Prepare the employee record for transmission

        Status: NEW => READY
        """
        if self.status not in [EmployeeRecord.Status.NEW, EmployeeRecord.Status.REJECTED]:
            raise ValidationError(self.ERROR_EMPLOYEE_RECORD_INVALID_STATE)

        profile = self.job_seeker.jobseeker_profile

        if not profile.hexa_address_filled:
            # Format job seeker address
            profile.update_hexa_address()

        self.clean()

        # If we reach this point, the employee record is ready to be serialized
        # and can be sent to ASP
        self.status = self.Status.READY
        self.save()

    def update_as_sent(self, asp_filename, line_number):
        """
        An employee record is sent to ASP via a JSON file,
        The file name is stored for further feedback processing (also done via a file)

        Status: READY => SENT
        """
        if not self.status == EmployeeRecord.Status.READY:
            raise ValidationError(self.ERROR_EMPLOYEE_RECORD_INVALID_STATE)

        self.clean()

        self.asp_batch_file = asp_filename
        self.asp_batch_line_number = line_number
        self.status = EmployeeRecord.Status.SENT
        self.save()

    def update_as_rejected(self, code, label):
        """
        Update status after an ASP rejection of the employee record

        Status: SENT => REJECTED
        """
        if not self.status == EmployeeRecord.Status.SENT:
            raise ValidationError(self.ERROR_EMPLOYEE_RECORD_INVALID_STATE)

        self.clean()
        self.status = EmployeeRecord.Status.REJECTED
        self.asp_processing_code = code
        self.asp_processing_label = label
        self.save()

    def update_as_accepted(self, code, label, archive):
        if not self.status == EmployeeRecord.Status.SENT:

itou/templates/employee_record/includes/create_step_1.html
{% load bootstrap4 %}

<h4>Etat civil du salarié</h4>

{% bootstrap_form_errors form %}

<form method="post" action="" class="js-prevent-multiple-submit">
    {% csrf_token %}

    {% bootstrap_field form.title %}
    {% bootstrap_field form.first_name %}
    {% bootstrap_field form.last_name %}

    {% bootstrap_field form.birthdate %}
    {% bootstrap_field form.birth_country %}
    {% bootstrap_field form.insee_commune %}
    {% bootstrap_field form.insee_commune_code %}

    {% buttons %}
        <a class="btn btn btn-outline-secondary" href="#">Annuler</a>
        <button type="submit" class="btn btn-primary">Continuer</button>
    {% endbuttons %}
</form>

itou/templates/employee_record/includes/create_step_2.html
{% load bootstrap4 %}

<h4>Domiciliation du salarié</h4>

<form method="POST" action="{% url "employee_record_views:create_step_2" job_application.id %}" class="js-prevent-multiple-submit">
    {% csrf_token %}

    {% bootstrap_field form.address_line_1 %}
    {% bootstrap_field form.address_line_2 %}

    <div class="row">
        <div class="col-md-3">
            {% bootstrap_field form.post_code %}
        </div>
        <div class="col-md-9">
            {% bootstrap_field form.city %}
        </div>
    </div>

    <div class="alert alert-warning">
        <small>
        <div class="mt-1">    
            Merci de bien vouloir vérifier si le format d'adresse ci-dessous (HEXA) correspond bien
            à l'adresse de l'employé.
        </div>
        <div class="mt-1">    
            <b>Si l'adresse ne correspond pas</b>, merci de mettre à jour l'adresse à l'aide du formulaire
            et de cliquer sur le bouton <b>"Mettre à jour"</b> et de repéter l'opération jusqu'à obtention d'une adresse correcte.
        </div>
        </small>
    </div>

    <div class="alert alert-secondary">
        <div class="row">
            <div class="col-md-3">Numéro</div>
            <div class="col-md-9"><b>{{ profile.hexa_lane_number }} {{ profile.hexa_std_extension }}{{ profile.hexa_non_std_extension }}</b></div>
        </div>
        <div class="row">
            <div class="col-md-3">Voie</div>
            <div class="col-md-9"><b>{{ profile.hexa_lane_name }}</b></div>
        </div>
        <div class="row">
            <div class="col-md-3">Commune</div>
            <div class="col-md-9">
                <b>{{ profile.hexa_post_code }} {{ profile.hexa_commune.name }}</b>
                <br>
                <span><small>(code INSEE : {{ profile.hexa_commune.code }})</small></span>
            </div>
        </div>
    </div>

    <div class="mt-2 text-right">
        {% buttons %}
            <button type="submit" class="btn btn-primary">Mettre à jour</button>
        {% endbuttons %}
    </div>

    {% bootstrap_field form.phone %}
    {% bootstrap_field form.email %}

</form>


<a class="btn btn btn-outline-secondary" href="{% url "employee_record_views:create" job_application.id %}">Précédent</a>
<a class="btn btn btn-outline-primary" href="{% url "employee_record_views:create_step_3" job_application.id %}">Continuer</a>

itou/templates/employee_record/includes/create_step_3.html
{% load bootstrap4 %}
{% load static %}
{% load folds %}

<h4>Situation du salarié</h4>

<form method="POST" action="{% url "employee_record_views:create_step_3" job_application.id %}" class="js-prevent-multiple-submit">
        
    {% bootstrap_form_errors form %}

    {% csrf_token %}

    {% bootstrap_field form.education_level %}
    {% bootstrap_field form.resourceless %}

    {% bootstrap_field form.pole_emploi %}
    <div id="fold_pole_emploi" class="ml-1 pl-4 border-left border-primary {{ form.pole_emploi.value|fold_class }}">
        {% bootstrap_field form.pole_emploi_id %}
        {% bootstrap_field form.pole_emploi_since %}
    </div>

    {% bootstrap_field form.rqth_employee %}
    {% bootstrap_field form.oeth_employee %}
    {% bootstrap_field form.has_rsa_allocation %}

    {% bootstrap_field form.ass_allocation %}
    <div id="fold_ass_allocation" class="ml-1 pl-4 border-left border-primary {{ form.ass_allocation.value|fold_class }}">
        {% bootstrap_field form.ass_allocation_since %}
    </div>
    
    {% bootstrap_field form.aah_allocation %}
    <div id="fold_aah_allocation" class="ml-1 pl-4 border-left border-primary {{ form.aah_allocation.value|fold_class }}">
        {% bootstrap_field form.aah_allocation_since %}
    </div>

    {% bootstrap_field form.ata_allocation %}
    <div id="fold_ata_allocation" class="ml-1 pl-4 border-left border-primary {{ form.ata_allocation.value|fold_class }}">
        {% bootstrap_field form.ata_allocation_since %}
    </div>

    {% buttons %}
        <a class="btn btn btn-outline-secondary" href="{% url "employee_record_views:create_step_2" job_application.id %}">Précédent</a>
        <button type="submit" class="btn btn-primary">Continuer</button>
    {% endbuttons %}

</form>


{# A vérifier / optimiser #}

<script src="{% static "vendor/jquery-3.4.1/jquery.min.js" %}"></script>
<script>
    function toggleFold(elt) {
        var fold = '#fold_' + elt.name 
        if ($(elt).is(':checked')) {
            $(fold).removeClass("d-none")
        } else {
            $(fold).addClass("d-none")
        }}
</script>

itou/templates/employee_record/includes/list_item.html
<div class="card my-4">

    <div class="card-header">
        <b>{{ item.job_seeker.get_full_name|title }}</b>
    </div>

    <div class="card-body">

        <div class="row">

            <div class="col-md-7">
                <p class="m-0">Début de contrat : <b>{{ item.hiring_start_at }}</b></p>
                <p class="m-0">Fin de contrat : <b>{{ item.hiring_end_at }}</b></p>
                <p class="m-0">Numéro de PASS IAE (agrément) : <b>{{ item.approval.number_with_spaces }}</b></p>
            </div>

            {# Statuses. #}
            {% if form.status.value == "SENT" %}
                <div class="col-md-5 text-right">
                    <p class="m-0 pt-1 badge badge-warning">Transmise à l'ASP le : <b>{{ item.updated_at }}</b></p>
                </div>
            {% elif form.status.value == "REJECTED" %}
                <div class="col-md-5 text-right">
                    <p class="m-0 pt-1 badge badge-danger">Rejetée par l'ASP le : <b>{{ item.updated_at }}</b></p>
                </div>
            {% elif form.status.value == "PROCESSED" %}
                <div class="col-md-5 text-right">
                    <p class="m-0 pt-1 badge badge-success">Validée par l'ASP le : <b>{{ item.updated_at }}</b></p>
                </div>
            {% endif %}

        </div>

        {# Actions. #}
        {% if form.status.value == "NEW" %}
            <div>
                <a href="{% url "employee_record_views:create" item.id %}" class="btn btn-outline-primary float-right">Créer la fiche salarié</a>
            </div>
        {% elif form.status.value == "SENT" %}
            <div>
                <a href="#" class="btn btn-outline-primary float-right">Voir le détail de la fiche salarié</a>
            </div>
        {% elif form.status.value == "REJECTED" %}
            <div>
                <a href="#" class="btn btn-outline-primary float-right">Modifier la fiche salarié</a>
            </div>
        {% elif form.status.value == "PROCESSED" %}
            <div>
                <a href="#" class="btn btn-outline-primary float-right">Voir le détail de la fiche salarié</a>
            </div>
        {% endif %}

    </div>

</div>