itou/api/urls.py
from django.urls import path
from rest_framework.authtoken import views as auth_views

from itou.api import views


# https://docs.djangoproject.com/en/dev/topics/http/urls/#url-namespaces-and-included-urlconfs
app_name = "api"

urlpatterns = [
    # TokenAuthentication endpoint to get token from login/password.
    path("token-auth/", auth_views.obtain_auth_token, name="token-auth"),
    path("dummy-employee-records/", views.DummyEmployeeRecordList.as_view(), name="dummy-employee-records"),
]

itou/www/dashboard/urls.py
from django.urls import path

from itou.www.dashboard import views


# https://docs.djangoproject.com/en/dev/topics/http/urls/#url-namespaces-and-included-urlconfs
app_name = "dashboard"

urlpatterns = [
    path("", views.dashboard, name="index"),
    path("edit_user_email", views.edit_user_email, name="edit_user_email"),
    path("edit_user_info", views.edit_user_info, name="edit_user_info"),
    path("edit_user_preferences", views.edit_user_preferences, name="edit_user_preferences"),
    path("edit_job_seeker_info/<uuid:job_application_id>", views.edit_job_seeker_info, name="edit_job_seeker_info"),
    path("switch_siae", views.switch_siae, name="switch_siae"),
    path(
        "switch_prescriber_organization", views.switch_prescriber_organization, name="switch_prescriber_organization"
    ),
]

itou/prescribers/models.py
from django.conf import settings
from django.contrib.gis.db.models.functions import Distance
from django.contrib.gis.measure import D
from django.contrib.postgres.search import TrigramSimilarity
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Prefetch
from django.urls import reverse
from django.utils import timezone
from django.utils.http import urlencode

from itou.utils.address.models import AddressMixin
from itou.utils.emails import get_email_message
from itou.utils.validators import validate_code_safir, validate_siret


class PrescriberOrganizationQuerySet(models.QuerySet):
    def member_required(self, user):
        if user.is_superuser:
            return self
        return self.filter(members=user, members__is_active=True)

    def autocomplete(self, search_string, limit=10):
        queryset = (
            self.annotate(similarity=TrigramSimilarity("name", search_string))
            .filter(similarity__gt=0.1)
            .order_by("-similarity")
        )
        return queryset[:limit]

    def by_safir_code(self, safir_code):
        return self.filter(code_safir_pole_emploi=safir_code).first()

    def within(self, point, distance_km):
        return (
            self.filter(coords__distance_lte=(point, D(km=distance_km)))
            .annotate(distance=Distance("coords", point))
            .order_by("distance")
        )

    def prefetch_active_memberships(self):
        qs = PrescriberMembership.objects.active().select_related("user")
        return self.prefetch_related(Prefetch("prescribermembership_set", queryset=qs))


class PrescriberOrganizationManager(models.Manager):
    def get_accredited_orgs_for(self, org):
        """
        Returns organizations accredited by the given organization.
        """
        if org.kind == self.model.Kind.DEPT and org.is_authorized:
            return self.filter(department=org.department, is_brsa=True)
        return self.none()


class PrescriberOrganization(AddressMixin):  # Do not forget the mixin!
    """
    The organization of a prescriber, e.g.: Pôle emploi, missions locales, Cap emploi etc.

    A "prescriber" is always represented by a User object with the `is_prescriber` flag set to `True`.

    The "prescriber" has the possibility of being a member of an organisation represented by a
    `PrescriberOrganization` object through `PrescriberMembership`.

    However it is not required for a "prescriber" to be a member of an organization.

    There are 3 possible cases:

    Case 1
        A "prescriber" is alone (e.g. "éducateur de rue"). In this case there is only a `User` object
            - User.is_prescriber = True

    Case 2
        A "prescriber" is a member of an organization (e.g. an association of unemployed people etc.)
        and uses the platform with 0 or n collaborators.
        In this case there are 3 objects:
            - User.is_prescriber = True
            - PrescriberOrganization.is_authorized = False
            - PrescriberMembership

    Case 3
        This case is a variant of case 2 where the organization is "authorized" at national level or by
        the Prefect (e.g. Pôle emploi, CCAS, Cap emploi…). This is similar to case 2  with an additional
        flag for the organization:
            - User.is_prescriber = True
            - PrescriberOrganization.is_authorized = True
            - PrescriberMembership

    In the last 2 cases, there can be n members by organization.

    In case 1 and case 2, we talk about "orienteur" in French.

    In case 3, we talk about "prescripteur habilité" in French.
    """

    class Kind(models.TextChoices):
        PE = "PE", "Pôle emploi"
        CAP_EMPLOI = "CAP_EMPLOI", "CAP emploi"
        ML = "ML", "Mission locale"
        DEPT = "DEPT", "Service social du conseil départemental"
        SPIP = "SPIP", "SPIP - Service pénitentiaire d'insertion et de probation"
        PJJ = "PJJ", "PJJ - Protection judiciaire de la jeunesse"
        CCAS = ("CCAS", "CCAS - Centre communal d'action sociale ou centre intercommunal d'action sociale")
        PLIE = "PLIE", "PLIE - Plan local pour l'insertion et l'emploi"
        CHRS = "CHRS", "CHRS - Centre d'hébergement et de réinsertion sociale"
        CIDFF = ("CIDFF", "CIDFF - Centre d'information sur les droits des femmes et des familles")
        PREVENTION = "PREVENTION", "Service ou club de prévention"
        AFPA = ("AFPA", "AFPA - Agence nationale pour la formation professionnelle des adultes")
        PIJ_BIJ = "PIJ_BIJ", "PIJ-BIJ - Point/Bureau information jeunesse"
        CAF = "CAF", "CAF - Caisse d'allocation familiale"
        CADA = "CADA", "CADA - Centre d'accueil de demandeurs d'asile"
        ASE = "ASE", "ASE - Aide sociale à l'enfance"
        CAVA = "CAVA", "CAVA - Centre d'adaptation à la vie active"
        CPH = "CPH", "CPH - Centre provisoire d'hébergement"
        CHU = "CHU", "CHU - Centre d'hébergement d'urgence"
        OACAS = (
            "OACAS",
            (
                "OACAS - Structure porteuse d'un agrément national organisme "
                "d'accueil communautaire et d'activité solidaire"
            ),
        )
        OTHER = "OTHER", "Autre"

    class AuthorizationStatus(models.TextChoices):
        NOT_SET = "NOT_SET", "Habilitation en attente de validation"
        VALIDATED = "VALIDATED", "Habilitation validée"
        REFUSED = "REFUSED", "Validation de l'habilitation refusée"
        NOT_REQUIRED = "NOT_REQUIRED", "Pas d'habilitation nécessaire"

    # Rules:
    # - a SIRET was not mandatory in the past (some entries still have a "blank" siret)
    # - a SIRET is now required for all organizations, except for Pôle emploi agencies
    # - a SIRET now can have several kinds
    # This is enforced at the DB level with a `unique_together` constraint + `null=True`.
    # `null=True` is required to avoid unique constraint violations when saving multiple
    # objects with "blank" values (e.g. Pôle emploi agencies or old entries that existed
    # prior to the mandatory siret).
    # See https://docs.djangoproject.com/en/3.1/ref/models/fields/#null
    siret = models.CharField(verbose_name="Siret", max_length=14, validators=[validate_siret], null=True, blank=True)
    kind = models.CharField(verbose_name="Type", max_length=20, choices=Kind.choices, default=Kind.OTHER)
    is_brsa = models.BooleanField(
        verbose_name="Conventionné pour le suivi des BRSA",
        default=False,
        help_text="Indique si l'organisme est conventionné par le conseil départemental pour le suivi des BRSA.",
    )
    name = models.CharField(verbose_name="Nom", max_length=255)
    phone = models.CharField(verbose_name="Téléphone", max_length=20, blank=True)
    email = models.EmailField(verbose_name="E-mail", blank=True)
    website = models.URLField(verbose_name="Site web", blank=True)
    description = models.TextField(verbose_name="Description", blank=True)
    members = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        verbose_name="Membres",
        through="PrescriberMembership",
        blank=True,
        through_fields=("organization", "user"),
    )
    is_authorized = models.BooleanField(
        verbose_name="Habilitation",
        default=False,
        help_text="Précise si l'organisation est habilitée par le Préfet.",
    )
    code_safir_pole_emploi = models.CharField(
        verbose_name="Code Safir",
        help_text="Code unique d'une agence Pole emploi.",
        validators=[validate_code_safir],
        max_length=5,
        blank=True,
        # Empty values are stored as NULL if both `null=True` and `unique=True` are set.
        # This avoids unique constraint violations when saving multiple objects with blank values.
        null=True,
        unique=True,
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name="Créé par",
        related_name="created_prescriber_organization_set",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )
    created_at = models.DateTimeField(verbose_name="Date de création", default=timezone.now)
    updated_at = models.DateTimeField(verbose_name="Date de modification", blank=True, null=True)

    authorization_status = models.CharField(
        verbose_name="Statut de l'habilitation",
        max_length=20,
        choices=AuthorizationStatus.choices,
        default=AuthorizationStatus.NOT_SET,
    )
    authorization_updated_at = models.DateTimeField(verbose_name="Date de MAJ du statut de l'habilitation", null=True)
    authorization_updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name="Dernière MAJ de l'habilitation par",
        related_name="authorization_status_set",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )

    objects = PrescriberOrganizationManager.from_queryset(PrescriberOrganizationQuerySet)()

    class Meta:
        verbose_name = "Organisation"
        verbose_name_plural = "Organisations"
        # This DB constraint works with null fields, but not with blank ones
        # If both org1 and org2 are created:
        # OK  => org1: (kind="ML", siret=None) + org2: (kind="ML", siret=None)
        # OK  => org1: (kind="ML", siret="12345678900000") + org2; (kind="ML", siret=None)
        # OK =>  org1: (kind="ML", siret="12345678900000") + org2; (kind="PLIE", siret="12345678900000")
        # NOK => org1: (kind="ML", siret="12345678900000") + org2; (kind="ML", siret="12345678900000")
        unique_together = ("siret", "kind")

    def __str__(self):
        return f"{self.name}"

    def save(self, *args, **kwargs):
        if self.pk:
            self.updated_at = timezone.now()
        return super().save(*args, **kwargs)

    def clean(self, *args, **kwargs):
        super().clean()
        self.clean_code_safir_pole_emploi()
        self.clean_siret()

    def clean_code_safir_pole_emploi(self):

itou/templates/prescribers/card.html
{% extends "layout/content_small.html" %}
{% load format_filters %}

{% block title %}{{ siae.display_name }}{{ block.super }}{% endblock %}

{% block content %}

    <p>
        <b>Prescripteur habilité</b>
        -
        <i>{{ prescriber_org.get_kind_display }}</i>
    </p>

    <hr>

    <h1>
        {{ prescriber_org.name }}
    </h1>

    <p class="text-muted">
        {{ prescriber_org.address_line_1 }},
        {% if prescriber_org.address_line_2 %}{{ prescriber_org.address_line_2 }},{% endif %}
        {{ prescriber_org.post_code }} {{ prescriber_org.city }}
    </p>

    {% if prescriber_org.description %}
        <hr>
        <div>{{ prescriber_org.description|linebreaks }}</div>
    {% endif %}

    {% if user.is_authenticated and prescriber_org.email %}
        <p>
            {% include "includes/icon.html" with icon="mail" title="E-mail" %}
            <a href="mailto:{{ prescriber_org.email }}">{{ prescriber_org.email }}</a>
        </p>
    {% endif %}

    {% if user.is_authenticated and prescriber_org.phone %}
        <p>
            {% include "includes/icon.html" with icon="phone" title="Téléphone" %}
            <a href="tel:{{ prescriber_org.phone }}">{{ prescriber_org.phone|format_phone }}</a>
        </p>
    {% endif %}

    {% if prescriber_org.website %}
        <p>
            {% include "includes/icon.html" with icon="external-link" title="Site Internet" %}
            <a href="{{ prescriber_org.website }}" rel="noopener" target="_blank">{{ prescriber_org.website }}</a>
        </p>
    {% endif %}

    {% if back_url %}
        <hr>
        <p>
            <a href="{{ back_url }}">Retour</a>
        </p>
    {% endif %}

{% endblock %}

itou/templates/prescribers/deactivate_member.html
{% extends "layout/content.html" %}

{% block title %}Retrait d'un collaborateur{{ block.super }}{% endblock %}

{% block content %}
    {% with base_url="prescribers_views" %}
        {% include "includes/deactivate_member.html" %}    
    {% endwith %}
{% endblock %}

itou/templates/prescribers/edit_organization.html
{% extends "layout/content_small.html" %}
{% load bootstrap4 %}

{% block title %}Modifier votre organisation{{ block.super }}{% endblock %}

{% block content %}

<h1>Modifier votre organisation</h1>

<h2 class="text-muted">
    {{ organization.display_name }}
</h2>

<div class="alert alert-info" role="alert">
    Les coordonnées de contact de votre organisation sont visibles par tous les utilisateurs connectés.
</div>

<form method="post" action="" class="js-prevent-multiple-submit">

    {% csrf_token %}

    {% bootstrap_form form %}

    {% buttons %}
        <a class="btn btn-secondary" href="{% url 'dashboard:index' %}">Annuler</a>
        <button type="submit" class="btn btn-primary">Enregistrer</button>
    {% endbuttons %}

</form>

{% endblock %}

itou/templates/prescribers/list_accredited_organizations.html
{% extends "layout/content.html" %}

{% block title %}Liste des organisations conventionnées{{ block.super }}{% endblock %}

{% block content %}

    <h1>
        Liste des organisations conventionnées
    </h1>

    <h2>
         <span class="text-muted">{{ prescriber_org.display_name }}</span>
    </h2>

    <div class="alert alert-info" role="alert">
        Seuls les administrateurs peuvent voir cette liste.
    </div>

    <hr>

    {% if not accredited_orgs %}

        <div class="alert alert-secondary" role="info">
            Aucun résultat.
        </div>

    {% else %}

        <ul>

            {% for org in accredited_orgs %}

                <li>

                    <p>
                        <b>{{ org.display_name }}</b>
                         -
                         <span class="text-muted">{{ org.city }}</span>
                         <br>
                        <a
                            data-toggle="collapse"
                            href="#collapse_membership_{{ org.pk }}"
                            role="button"
                            aria-expanded="false"
                            aria-controls="collapse_membership_{{ org.pk }}"
                        >
                            Voir les membres
                        </a>
                    </p>

                    <div class="collapse" id="collapse_membership_{{ org.pk }}">

                        <div class="table-responsive">
                            <table class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Nom</th>
                                        <th scope="col">Prénom</th>
                                        <th scope="col">Email</th>
                                        <th scope="col">Administrateur</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for membership in org.prescribermembership_set.all %}
                                        <tr>
                                            <th scope="row">{{ forloop.counter }}</th>
                                            <td>
                                                {{ membership.user.last_name|title }}
                                            </td>
                                            <td>
                                                {{ membership.user.first_name|title }}
                                            </td>
                                            <td>
                                                <a href="mailto:{{ membership.user.email }}">
                                                    {{ membership.user.email }}
                                                </a>
                                            </td>
                                            <td>
                                                {% if membership.is_admin %}
                                                    {% include "includes/icon.html" with icon="check" %}
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>

                    </div>

                </li>

            {% endfor %}

        </ul>

    {% endif %}

{% endblock %}

itou/templates/prescribers/members.html
{% extends "layout/content.html" %}

{% block title %}Collaborateurs{{ block.super }}{% endblock %}

{% block content %}

<h1>Collaborateurs</h1>

<h2 class="text-muted">
    {{ organization.display_name }}
</h2>

<div class="alert alert-info" role="alert">
    Vous êtes connecté en tant que <b>{{ user.get_full_name }}</b> ({{ user.email }})
</div>

{% with active_admin_members=organization.active_admin_members base_url="prescribers_views" %}
    {% include "includes/members.html" %}
{% endwith %}

<a href="{% url 'invitations_views:invite_prescriber_with_org' %}" class="align-self-center">
    <button class="btn btn-primary mb-1 w-100 w-sm-auto mt-2">Inviter des collaborateurs</button>
</a>

{% if pending_invitations %}
    {% include "invitations_views/includes/pending_invitations.html" %}
{% endif %}

{% endblock %}

itou/templates/prescribers/update_admins.html
{% extends "layout/content.html" %}

{% block title %}Gestion des administrateurs{{ block.super }}{% endblock %}

{% block content %}
    {% with base_url="prescribers_views" %}
        {% include "includes/update_admin.html" %}
    {% endwith %}
{% endblock %}