itou/api/urls.py
from django.urls import path
from rest_framework.authtoken import views as auth_views

from itou.api import views


# https://docs.djangoproject.com/en/dev/topics/http/urls/#url-namespaces-and-included-urlconfs
app_name = "api"

urlpatterns = [
    # TokenAuthentication endpoint to get token from login/password.
    path("token-auth/", auth_views.obtain_auth_token, name="token-auth"),
    path("dummy-employee-records/", views.DummyEmployeeRecordList.as_view(), name="dummy-employee-records"),
]

itou/siaes/urls.py
from django.urls import path, re_path

from itou.siaes import views


# https://docs.djangoproject.com/en/dev/topics/http/urls/#url-namespaces-and-included-urlconfs
app_name = "siae"

urlpatterns = [
    re_path(r"^(?P<siret>\d{14})/card$", views.card, name="card"),
    path("search", views.search, name="search"),
    re_path(
        r"^(?P<siret>\d{14})/configure_jobs$",
        views.configure_jobs,
        name="configure_jobs",
    ),
]

itou/www/dashboard/urls.py
from django.urls import path

from itou.www.dashboard import views


# https://docs.djangoproject.com/en/dev/topics/http/urls/#url-namespaces-and-included-urlconfs
app_name = "dashboard"

urlpatterns = [
    path("", views.dashboard, name="index"),
    path("edit_user_email", views.edit_user_email, name="edit_user_email"),
    path("edit_user_info", views.edit_user_info, name="edit_user_info"),
    path("edit_user_preferences", views.edit_user_preferences, name="edit_user_preferences"),
    path("edit_job_seeker_info/<uuid:job_application_id>", views.edit_job_seeker_info, name="edit_job_seeker_info"),
    path("switch_siae", views.switch_siae, name="switch_siae"),
    path(
        "switch_prescriber_organization", views.switch_prescriber_organization, name="switch_prescriber_organization"
    ),
]

itou/accounts/views/dashboard.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy

from allauth.account.views import PasswordChangeView


@login_required
def dashboard(request, template_name="account_itou/dashboard.html"):

    context = {}
    return render(request, template_name, context)


class ItouPasswordChangeView(PasswordChangeView):
    """
    https://github.com/pennersr/django-allauth/issues/468
    """

    success_url = reverse_lazy("accounts:dashboard")


password_change = login_required(ItouPasswordChangeView.as_view())

itou/accounts/views/signup.py
"""
Handle multiple user types sign up with django-allauth.
"""
from allauth.account.views import SignupView

from django.db import transaction

from itou.accounts import forms


class PrescriberSignupView(SignupView):

    form_class = forms.PrescriberSignupForm
    template_name = "account_itou/signup_prescriber.html"

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        """Enforce atomicity."""
        return super().post(request, *args, **kwargs)


class SiaeSignupView(SignupView):

    form_class = forms.SiaeSignupForm
    template_name = "account_itou/signup_siae.html"

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        """Enforce atomicity."""
        return super().post(request, *args, **kwargs)


class JobSeekerSignupView(SignupView):

    form_class = forms.JobSeekerSignupForm
    template_name = "account_itou/signup_job_seeker.html"

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        """Enforce atomicity."""
        return super().post(request, *args, **kwargs)

itou/www/dashboard/views.py
from allauth.account.views import LogoutView, PasswordChangeView
from django.conf import settings
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.utils.http import urlencode
from django.views.decorators.http import require_POST

from itou.job_applications.models import JobApplication, JobApplicationWorkflow
from itou.prescribers.models import PrescriberOrganization
from itou.siaes.models import Siae
from itou.utils.perms.siae import get_current_siae_or_404
from itou.utils.urls import get_safe_url
from itou.www.dashboard.forms import EditNewJobAppEmployersNotificationForm, EditUserEmailForm, EditUserInfoForm


@login_required
def dashboard(request, template_name="dashboard/dashboard.html"):
    can_show_financial_annexes = False
    can_show_employee_records = False
    job_applications_categories = []

    if request.user.is_siae_staff:
        siae = get_current_siae_or_404(request)
        can_show_financial_annexes = siae.convention_can_be_accessed_by(request.user)
        can_show_employee_records = siae.can_use_employee_record
        job_applications_categories = [
            {
                "name": "Candidatures à traiter",
                "states": [JobApplicationWorkflow.STATE_NEW, JobApplicationWorkflow.STATE_PROCESSING],
                "icon": "user-plus",
                "badge": "badge-danger",
            },
            {
                "name": "Candidatures acceptées ou mises en liste d'attente",
                "states": [JobApplicationWorkflow.STATE_ACCEPTED, JobApplicationWorkflow.STATE_POSTPONED],
                "icon": "user-check",
                "badge": "badge-secondary",
            },
            {
                "name": "Candidatures refusées/annulées",
                "states": [
                    JobApplicationWorkflow.STATE_REFUSED,
                    JobApplicationWorkflow.STATE_CANCELLED,
                    JobApplicationWorkflow.STATE_OBSOLETE,
                ],
                "icon": "user-x",
                "badge": "badge-secondary",
            },
        ]
        job_applications = siae.job_applications_received.values("state").all()
        for category in job_applications_categories:
            category["counter"] = len([ja for ja in job_applications if ja["state"] in category["states"]])
            category[
                "url"
            ] = f"{reverse('apply:list_for_siae')}?{'&'.join([f'states={c}' for c in category['states']])}"

    context = {
        "lemarche_regions": settings.LEMARCHE_OPEN_REGIONS,
        "job_applications_categories": job_applications_categories,
        "can_show_financial_annexes": can_show_financial_annexes,
        "can_show_employee_records": can_show_employee_records,
    }

    return render(request, template_name, context)


class ItouPasswordChangeView(PasswordChangeView):
    """
    https://github.com/pennersr/django-allauth/issues/468
    """

    success_url = reverse_lazy("dashboard:index")


password_change = login_required(ItouPasswordChangeView.as_view())


class ItouLogoutView(LogoutView):
    def post(self, *args, **kwargs):
        """
        We overload this method so that we can process the PEAMU callback
        when the user logs out.
        Original code:
        https://github.com/pennersr/django-allauth/blob/master/allauth/account/views.py#L775
        """
        peamu_id_token = self.request.user.peamu_id_token
        ajax_response = super().post(*args, **kwargs)
        if peamu_id_token:
            hp_url = self.request.build_absolute_uri("/")
            params = {"id_token_hint": peamu_id_token, "redirect_uri": hp_url}
            peamu_logout_url = f"{settings.PEAMU_AUTH_BASE_URL}/compte/deconnexion?{urlencode(params)}"
            return HttpResponseRedirect(peamu_logout_url)
        else:
            return ajax_response


logout = login_required(ItouLogoutView.as_view())


@login_required
def edit_user_email(request, template_name="dashboard/edit_user_email.html"):
    form = EditUserEmailForm(data=request.POST or None, user_email=request.user.email)
    if request.method == "POST" and form.is_valid():
        with transaction.atomic():
            request.user.email = form.cleaned_data["email"]
            request.user.save()
            request.user.emailaddress_set.first().delete()
        auth.logout(request)
        return HttpResponseRedirect("/")

    context = {
        "form": form,
    }

    return render(request, template_name, context)


@login_required
def edit_user_info(request, template_name="dashboard/edit_user_info.html"):
    """
    Edit a user.
    """
    dashboard_url = reverse_lazy("dashboard:index")
    prev_url = get_safe_url(request, "prev_url", fallback_url=dashboard_url)
    form = EditUserInfoForm(instance=request.user, editor=request.user, data=request.POST or None)
    extra_data = request.user.externaldataimport_set.pe_sources().first()

    if request.method == "POST" and form.is_valid():
        form.save()
        messages.success(request, "Mise à jour de vos informations effectuée !")
        success_url = get_safe_url(request, "success_url", fallback_url=dashboard_url)
        return HttpResponseRedirect(success_url)

    context = {
        "extra_data": extra_data,
        "form": form,
        "prev_url": prev_url,
    }

    return render(request, template_name, context)


def user_can_edit_job_seeker_info(user, job_application, current_siae_pk=None):
    return (
        # Only when the information is not managed by job seekers themselves
        job_application.has_editable_job_seeker
        and (
            # Same sender (no SQL)
            job_application.sender_id == user.id
            # Member of the SIAE that offers the job application
            or (current_siae_pk and current_siae_pk == job_application.to_siae_id)
            # Member of the authorized prescriber organization who propose the candidate to the job application
            or user.is_prescriber_of_authorized_organization(job_application.sender_prescriber_organization_id)
        )
    )


@login_required
def edit_job_seeker_info(request, job_application_id, template_name="dashboard/edit_job_seeker_info.html"):
    job_application = get_object_or_404(JobApplication.objects.select_related("job_seeker"), pk=job_application_id)
    current_siae_pk = request.session.get(settings.ITOU_SESSION_CURRENT_SIAE_KEY)
    if not user_can_edit_job_seeker_info(request.user, job_application, current_siae_pk):
        raise PermissionDenied

    dashboard_url = reverse_lazy("dashboard:index")
    back_url = get_safe_url(request, "back_url", fallback_url=dashboard_url)
    form = EditUserInfoForm(instance=job_application.job_seeker, editor=request.user, data=request.POST or None)

    if request.method == "POST" and form.is_valid():
        form.save()
        messages.success(request, "Les informations du candidat ont été mises à jour.")
        return HttpResponseRedirect(back_url)

    context = {
        "form": form,
        "job_application": job_application,
        "prev_url": back_url,
    }

    return render(request, template_name, context)


@login_required
@require_POST
def switch_siae(request):
    """
    Switch to the dashboard of another SIAE of the same SIREN.
    """
    dashboard_url = reverse_lazy("dashboard:index")

    pk = request.POST["siae_id"]
    queryset = Siae.objects.active_or_in_grace_period().member_required(request.user)
    siae = get_object_or_404(queryset, pk=pk)
    request.session[settings.ITOU_SESSION_CURRENT_SIAE_KEY] = siae.pk

    return HttpResponseRedirect(dashboard_url)


@login_required
@require_POST
def switch_prescriber_organization(request):
    """
    Switch prescriber organization for a user with multiple memberships.
    """
    dashboard_url = reverse_lazy("dashboard:index")

    pk = request.POST["prescriber_organization_id"]
    queryset = PrescriberOrganization.objects
    prescriber_organization = get_object_or_404(queryset, pk=pk)
    request.session[settings.ITOU_SESSION_CURRENT_PRESCRIBER_ORG_KEY] = prescriber_organization.pk

    return HttpResponseRedirect(dashboard_url)


@login_required
def edit_user_preferences(request, template_name="dashboard/edit_user_preferences.html"):
    if not request.user.is_siae_staff:
        raise PermissionDenied

    current_siae_pk = request.session.get(settings.ITOU_SESSION_CURRENT_SIAE_KEY)
    siae = get_object_or_404(Siae, pk=current_siae_pk)
    membership = request.user.siaemembership_set.get(siae=siae)
    new_job_app_notification_form = EditNewJobAppEmployersNotificationForm(
        recipient=membership, siae=siae, data=request.POST or None
    )

    dashboard_url = reverse_lazy("dashboard:index")
    back_url = get_safe_url(request, "back_url", fallback_url=dashboard_url)

    if request.method == "POST" and new_job_app_notification_form.is_valid():
        new_job_app_notification_form.save()
        messages.success(request, "Vos préférences ont été modifiées.")
        success_url = get_safe_url(request, "success_url", fallback_url=dashboard_url)
        return HttpResponseRedirect(success_url)

    context = {
        "new_job_app_notification_form": new_job_app_notification_form,
        "back_url": back_url,
    }

    return render(request, template_name, context)

itou/templates/account_itou/dashboard.html
{% extends "layout/content.html" %}
{% load i18n %}

{% block title %}{% trans "Tableau de bord" %}{{ block.super }}{% endblock %}

{% block content %}

    <h1>{% trans "Tableau de bord" %}</h1>

    <div class="card-deck mt-3">

        <div class="card">
            <h5 class="card-header">{% trans "Informations" %}</h5>
            <div class="card-body">
                <p class="card-text">
                    {% include "includes/icon.html" with icon="lock" %}
                    <a href="{% url 'account_change_password' %}">
                        {% trans "Modifier mon mot de passe" %}
                    </a>
                </p>
            </div>
        </div>

        {% if user.is_staff %}
            <div class="card">
                <h5 class="card-header">{% trans "Admin" %}</h5>
                <div class="card-body">
                    <p class="card-text">
                        {% include "includes/icon.html" with icon="key" %}
                        <a href="{% url 'admin:index' %}">
                            {% trans "Admin" %}
                        </a>
                    </p>
                </div>
            </div>
        {% endif %}

        {% if user.is_siae_staff and current_siae %}
            <div class="card">
                <h5 class="card-header">{% trans "Métiers" %}</h5>
                <div class="card-body">
                    <p class="card-text">
                        {% include "includes/icon.html" with icon="briefcase" %}
                        <a href="{% url 'siae:configure_jobs' siret=current_siae.siret %}">
                            {% trans "Configurez vos métiers" %}
                        </a>
                    </p>
                </div>
            </div>
        {% endif %}

    </div>

{% endblock %}

itou/templates/account_itou/signup.html
{% extends "layout/content.html" %}
{% load bootstrap4 %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "Inscription | Connexion" %}{{ block.super }}{% endblock %}


{% block content %}

    <div class="card-deck">

        <div class="card border-success">
            <div class="card-body">
                <h5 class="card-title">{% trans "Demandeur d'emploi" %}</h5>
            </div>
            <div class="list-group list-group-flush">
                <a class="list-group-item list-group-item-action" href="{% url 'accounts:job_seeker_signup' %}">
                    {% include "includes/icon.html" with icon="user-plus" %} {% trans "Inscription" %}
                </a>
                <a class="list-group-item list-group-item-action" href="{% url 'account_login' %}">
                    {% include "includes/icon.html" with icon="log-in" %} {% trans "Connexion" %}
                </a>
            </div>
            <img src="{% static 'photos/job_seeker.jpg' %}" class="card-img-bottom" alt="">
        </div>

        <div class="card border-warning">
            <div class="card-body">
                <h5 class="card-title">{% trans "Prescripteur" %}</h5>
            </div>
            <div class="list-group list-group-flush">
                <a class="list-group-item list-group-item-action" href="{% url 'accounts:prescriber_signup' %}">
                    {% include "includes/icon.html" with icon="user-plus" %} {% trans "Inscription" %}
                </a>
                <a class="list-group-item list-group-item-action" href="{% url 'account_login' %}">
                    {% include "includes/icon.html" with icon="log-in" %} {% trans "Connexion" %}
                </a>
            </div>
            <img src="{% static 'photos/prescriber.jpg' %}" class="card-img-bottom" alt="">
        </div>

        <div class="card border-primary">
            <div class="card-body">
                <h5 class="card-title">{% trans "SIAE" %}</h5>
            </div>
            <div class="list-group list-group-flush">
                <a class="list-group-item list-group-item-action" href="{% url 'accounts:siae_signup' %}">
                    {% include "includes/icon.html" with icon="user-plus" %} {% trans "Inscription" %}
                </a>
                <a class="list-group-item list-group-item-action" href="{% url 'account_login' %}">
                    {% include "includes/icon.html" with icon="log-in" %} {% trans "Connexion" %}
                </a>
            </div>
            <img src="{% static 'photos/employer.jpg' %}" class="card-img-bottom" alt="">
        </div>

    </div>

{% endblock %}

itou/templates/account_itou/signup_job_seeker.html
{% extends "layout/content_small.html" %}
{% load bootstrap4 %}
{% load i18n %}

{% block title %}{% trans "Demandeur d'emploi - Inscription" %}{{ block.super }}{% endblock %}


{% block content %}
<h1>
    {% trans "Demandeur d'emploi" %}
    <small class="text-muted">{% trans "Inscription" %}</small>
</h1>

<form method="post" action="{% url 'accounts:job_seeker_signup' %}" role="form">

    {% csrf_token %}

    {% bootstrap_form_errors form %}

    {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}">
    {% endif %}

    {% bootstrap_field form.first_name %}
    {% bootstrap_field form.last_name %}
    {% bootstrap_field form.email %}
    {% bootstrap_field form.password1 %}
    {% bootstrap_field form.password2 %}

    {% buttons %}
        <button type="submit" class="btn btn-primary">{% trans "Inscription" %}</button>
    {% endbuttons %}

</form>

<hr>

<p>
    <a href="{% url 'account_login' %}">{% trans "Vous avez déjà un compte ?" %}</a>
</p>
{% endblock %}

itou/templates/account_itou/signup_prescriber.html
{% extends "layout/content_small.html" %}
{% load bootstrap4 %}
{% load i18n %}

{% block title %}{% trans "Prescripteur - Inscription" %}{{ block.super }}{% endblock %}


{% block content %}
<h1>
    {% trans "Prescripteur" %}
    <small class="text-muted">{% trans "Inscription" %}</small>
</h1>

<form method="post" action="{% url 'accounts:prescriber_signup' %}" role="form">

    {% csrf_token %}

    {% bootstrap_form_errors form %}

    {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}">
    {% endif %}

    {% bootstrap_field form.first_name %}
    {% bootstrap_field form.last_name %}
    {% bootstrap_field form.email %}
    {% bootstrap_field form.siret %}
    {% bootstrap_field form.password1 %}
    {% bootstrap_field form.password2 %}

    {% buttons %}
        <button type="submit" class="btn btn-primary">{% trans "Inscription" %}</button>
    {% endbuttons %}

</form>

<hr>

<p>
    <a href="{% url 'account_login' %}">{% trans "Vous avez déjà un compte ?" %}</a>
</p>
{% endblock %}

itou/templates/account_itou/signup_siae.html
{% extends "layout/content_small.html" %}
{% load bootstrap4 %}
{% load i18n %}

{% block title %}{% trans "SIAE - Inscription" %}{{ block.super }}{% endblock %}


{% block content %}
<h1>
    {% trans "SIAE" %}
    <small class="text-muted">{% trans "Inscription" %}</small>
</h1>

<form method="post" action="{% url 'accounts:siae_signup' %}" role="form">

    {% csrf_token %}

    {% bootstrap_form_errors form %}

    {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}">
    {% endif %}

    {% bootstrap_field form.first_name %}
    {% bootstrap_field form.last_name %}
    {% bootstrap_field form.email %}
    {% bootstrap_field form.siret %}
    {% bootstrap_field form.password1 %}
    {% bootstrap_field form.password2 %}

    {% buttons %}
        <button type="submit" class="btn btn-primary">{% trans "Inscription" %}</button>
    {% endbuttons %}

</form>

<hr>

<p>
    <a href="{% url 'account_login' %}">{% trans "Vous avez déjà un compte ?" %}</a>
</p>
{% endblock %}